apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic-ingress
  namespace: magic-app
spec:
  ingressClassName: nginx
  rules:
    - host: magic.abhichaudhary.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: magic-service
                port:
                  number: 80
